name: Execute Terraform Plan
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
    branches:
      - main
      - master

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: installing terraform on ${{ runner.os }}
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Replacing key path from secret
        run: |
          touch id_rsa.pub
          echo "${{ secrets.ID_RSA_KEY }}" > id_rsa.pub
          sed -i 's/C\:\/Users\/Naveen.Singh\/.ssh\/id_rsa.pub/id_rsa.pub/' variables.tf
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_KEY }}"
          aws configure set region "${{ secrets.AWS_DEFAULT_REGION }}"
        shell: bash
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: terraform init
      - run: terraform plan
